[package]
version = "0.1.0"
name = "recursive-script"
edition = "2021"

[dependencies]
dirs = "5.0.1"
dotenv = "0.15.0"
hex = "0.4.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.121"
sp1-sdk = { version = "2.0.0", features = ["network"] }
tokio = { version = "1.39.2", features = ["full"] }

[build-dependencies]
sp1-helper = "2.0.0"
